"""
Confluence Page Summarizer Agent

Analyzes multiple Confluence page updates and extracts only important information to summarize.
"""

import logging
import os
from typing import Any, Dict, List, Optional

from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)


async def save_to_memory(content: str) -> None:
    """
    Adds Confluence page update content to the memory queue.

    Args:
        content: Content to save (summary of important page updates)
    """
    try:
        from app.queueing_extended import enqueue_memory_job

        memory_query = f"""The following is a recent Confluence page update. Please save this information if it contains useful information.

{content}

Use the `slack-memory-store` skill to categorize and save this information in the appropriate category.
Be sure to save anything related to your team members.
"""

        # Add job to memory queue (processed sequentially)
        await enqueue_memory_job({
            "memory_query": memory_query
        })
        logging.info(f"[CONFLUENCE_SUMMARIZER] Memory job enqueued")
    except Exception as e:
        logging.error(f"[CONFLUENCE_SUMMARIZER] Memory enqueue failed: {e}")


def create_system_prompt(state_prompt: str, bot_name: str, bot_role: str = "") -> str:
    """Creates a system prompt for the Confluence summarizer

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()
        bot_name: Bot name
        bot_role: Bot's role in the company

    Returns:
        str: System prompt including agent behavioral principles and tool usage principles
    """
    # Role section (only if configured)
    role_section = ""
    if bot_role:
        role_section = f"""

## Role in the Company
<bot_role>
{bot_role}
Prioritize storing information related to this role.
</bot_role>"""

    system_prompt = f"""You are {bot_name}, a virtual in-house employee communicating via Slack.

# Core Guidelines
You are an agent that analyzes Confluence page updates and extracts only important information.
You receive multiple Confluence page updates and filter and organize only the **work-related important content**.
Your core task is to organize and pass along only important page updates that a successor agent can reference in subsequent conversations.
{role_section}

{state_prompt}

## Workflow
<workflow>
1. Analyze the received batch of Confluence page updates.
2. Use Rovo MCP tools to retrieve the full page body content if necessary.
3. Evaluate the importance of each page based on the criteria.
4. Select and organize only the important page updates.
</workflow>

## Tool Usage Principles
<how_to_use_tool>
1. First use the `confluence-deep-reader` skill and follow the workflow to use Rovo MCP tools.
2. If the importance cannot be determined from title and modification information alone, you must retrieve the page body for accurate evaluation.
3. When calling tools with page ID, ensure you pass the correct ID.
4. Use page body retrieval only when the importance judgment is unclear to improve efficiency.
5. When creating files, always temporarily create them in `FILESYSTEM_BASE_DIR/checkers/tmp/` directory and delete them after work completion.
</how_to_use_tool>

## Core Behavioral Principles
<important_actions>
**Important Page Update Criteria:**
- Matters related to team members
- Project plans, schedules, milestone changes
- Technical documentation, API specifications, architecture changes
- Meeting minutes, decision records
- Policy, guideline, process changes
- Team notices, important issue tracking
</important_actions>

## Output Format
<output_format>
If there are important page updates:
- Organize the update details and categorize them by category.
- Include each page's title, URL, modifier, modification time, and key changes.

If there are no important page updates:
- Only output "No important page updates found."
</output_format>

## Guardrail Policy
<guardrails>
**Excluded items:**
- Personal memos, temporary work pages are not important.
- Do not save minor typo fixes, format changes.
- Exclude test pages.
- Exclude duplicate/repetitive content.

**File system access restrictions:**
- Never access files or directories outside FILESYSTEM_BASE_DIR
- Reading or modifying system files, home directories, configuration files is strictly prohibited
- File operations must be limited to within FILESYSTEM_BASE_DIR
</guardrails>"""

    return system_prompt


async def call_confluence_summarizer(
    pages: List[Dict[str, Any]]
) -> Optional[str]:
    """
    Analyzes a batch of Confluence pages and summarizes only important content.

    Args:
        pages: List of pages (including id, title, version, spaceId)

    Returns:
        Optional[str]: Query for memory storage (None if no important content)
    """
    if not pages:
        return None

    # Get settings and bot_name first
    from app.cc_agents.state_prompt import create_state_prompt
    from app.config.settings import get_settings

    settings = get_settings()
    bot_name = settings.BOT_NAME or "Bot"
    bot_role = settings.BOT_ROLE or ""

    # Create state_prompt (without slack_data, message_data)
    state_prompt = create_state_prompt()

    system_prompt = create_system_prompt(state_prompt, bot_name, bot_role)

    # Convert pages list to text
    pages_text = ""
    for idx, page in enumerate(pages, 1):
        page_id = page.get("id", "")
        title = page.get("title", "")
        version = page.get("version", {})
        modified_date = version.get("createdAt", "")
        modified_by_id = version.get("authorId", "Unknown")
        modified_by_email = version.get("authorEmail", "")
        space_id = page.get("spaceId", "")
        page_url = f"{settings.ATLASSIAN_CONFLUENCE_SITE_URL}/wiki/spaces/{space_id}/pages/{page_id}"

        # Modifier display (prefer email, fall back to ID)
        modified_by = modified_by_email if modified_by_email else modified_by_id

        pages_text += f"""
Page {idx}:
Page ID: {page_id}
Title: {title}
URL: {page_url}
Modifier: {modified_by}
Modification Time: {modified_date}

---
"""

    user_query = f"""Analyze the following {len(pages)} Confluence page updates:

{pages_text}

Be sure not to miss anything related to your team members."""

    # Atlassian MCP server configuration (remote)
    mcp_servers = {
        "atlassian": {
            "command": "npx",
            "args": ["mcp-cache", "npx", "-y", "mcp-remote", "http://localhost:9000/mcp"],
        }
    }

    options = ClaudeAgentOptions(
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_SIMPLE,
        permission_mode="bypassPermissions",
        allowed_tools=["*"],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
            "Write",
            "Edit",
            "NotebookEdit",
        ],
        setting_sources=['project'],
        cwd=os.getcwd(),
        mcp_servers=mcp_servers,
    )

    session_id = None
    result_message = ""

    # On context overflow, retry with /compact (maintain same client, max 2 times)
    max_retries = 2

    async with ClaudeSDKClient(options=options) as client:
        for attempt in range(max_retries + 1):
            try:
                # First attempt new session, retry continues with compacted session
                if session_id:
                    await client.query(user_query, session_id)
                else:
                    await client.query(user_query)

                async for message in client.receive_response():
                    if hasattr(message, 'subtype') and message.subtype == 'init':
                        session_id = message.data.get('session_id')
                        logging.info(f"[CONFLUENCE_SUMMARIZER] Session ID: {session_id}")

                    if isinstance(message, ResultMessage):
                        if "API Error" in message.result and "413" in message.result:
                            raise Exception(f"Context overflow in ResultMessage: {message.result}")

                        result_message = message.result.strip()
                        logging.info(f"[CONFLUENCE_SUMMARIZER] Result: {result_message[:100]}...")
                        break

                # Success - exit loop
                break

            except Exception as e:
                error_str = str(e)
                error_msg = error_str.lower()

                is_context_error = any([
                    "prompt is too long" in error_msg,
                    "context overflow" in error_msg,
                    "413" in error_msg,
                ])

                if is_context_error and attempt < max_retries:
                    logging.warning(f"[CONFLUENCE_SUMMARIZER] Context overflow detected (attempt {attempt + 1}/{max_retries}), executing /compact...")

                    # Execute /compact with same client (pass session_id)
                    await client.query("/compact", session_id)
                    async for msg in client.receive_response():
                        if isinstance(msg, ResultMessage):
                            logging.info(f"[CONFLUENCE_SUMMARIZER] /compact executed successfully")
                            break

                    # Continue with same client, original query retry
                    continue
                else:
                    # Max retries exceeded or other error
                    logging.error(f"[CONFLUENCE_SUMMARIZER] Error occurred: {e}")
                    return None

    # Return result after successful loop completion
    if result_message == "No important page updates found." or not result_message:
        logging.info("[CONFLUENCE_SUMMARIZER] No important pages found")
        return None

    return result_message