"""
Jira Ticket Extractor Agent

Analyzes assigned Jira tickets to extract important tasks and saves them to the database.
"""

import logging
import os
from typing import Any, Dict, List, Optional
from app.cc_agents.memory_retriever.agent import call_memory_retriever
from app.cc_tools.jira_tasks import create_jira_tasks_mcp_server
from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)


def create_system_prompt(state_prompt: str, bot_name: str) -> str:
    """Create system prompt for Jira task extractor

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()
        bot_name: Bot name

    Returns:
        str: System prompt containing agent behavior principles and tool usage guidelines
    """
    system_prompt = f"""You are {bot_name}, a virtual team member communicating via Slack.

# Core Guidelines
Analyze the provided Jira tickets and extract **tasks that you need to do**, then save them to the database.

{state_prompt}

## Core Action Principles
<important_actions>
1. Analyze the provided Jira tickets to extract tasks that you need to do.
2. Use Rovo MCP tools to get ticket details when needed.
3. If there are tasks to do, save them using `mcp__jira_tasks__add_jira_task`.
4. Summarize and output the processing results.
</important_actions>

## Tool Usage Principles
<how_to_use_tool>
1. If it's difficult to determine tasks from ticket information alone, use Rovo MCP tools to get detailed information.
2. Find the reporter's user_id, user_name, and channel_id from retrieved_memory.
   - The ticket contains the reporter's email, so search memory using that email.
3. The `text` parameter for `mcp__jira_tasks__add_jira_task` must follow this format:
   "{bot_name}, you have been assigned to perform [task name] via ticket [ticket key]. Please complete the task and set ticket [ticket key] to Done."
   Example: "{bot_name}, you have been assigned to perform code review via ticket PROJ-123. Please complete the task and set PROJ-123 to Done."
4. If a single ticket has multiple tasks, save each task **separately**.
5. If you cannot find user_id, user_name, and channel_id, do not save that task.
6. All assigned tickets are tasks you need to process, so extract tasks from each ticket.
7. If you need to create files, always create them temporarily in `FILESYSTEM_BASE_DIR/checkers/tmp/` directory and delete them after completing the task.
</how_to_use_tool>

## Guardrail Policy
<guardrails>
**File System Access Restrictions:**
- Never access files or directories outside FILESYSTEM_BASE_DIR
- Reading or modifying system files, home directories, or configuration files is strictly prohibited
- All file operations must be limited to within FILESYSTEM_BASE_DIR
</guardrails>"""

    return system_prompt


async def call_jira_task_extractor(issues: List[Dict[str, Any]]) -> Optional[str]:
    """
    Analyze Jira ticket batch, extract tasks to do, and save to database.

    Args:
        issues: List of issues (containing key and fields)

    Returns:
        Optional[str]: Processing result summary (None if no tasks)
    """
    if not issues:
        return None

    # Get settings and bot_name first
    from app.cc_agents.state_prompt import create_state_prompt
    from app.config.settings import get_settings

    settings = get_settings()
    bot_name = settings.BOT_NAME or "bot"

    # Convert issue list to text
    issues_text = ""
    for idx, issue in enumerate(issues, 1):
        issue_key = issue.get("key", "")
        fields = issue.get("fields", {})

        summary = fields.get("summary", "")
        status = fields.get("status", {}).get("name", "Unknown")
        priority = fields.get("priority", {}).get("name", "Medium")
        issue_type = fields.get("issuetype", {}).get("name", "Task")
        updated = fields.get("updated", "")
        created = fields.get("created", "")

        # Generate issue URL
        issue_url = f"{settings.ATLASSIAN_JIRA_SITE_URL}/browse/{issue_key}"

        # Include brief description
        description = fields.get("description", "")
        description_preview = (
            description[:200] + "..."
            if description and len(description) > 200
            else description
        )

        # Assignee info
        assignee = fields.get("assignee", {})
        assignee_name = assignee.get("displayName", "None") if assignee else "None"
        assignee_email = assignee.get("emailAddress", "") if assignee else ""

        # Reporter info
        reporter = fields.get("reporter", {})
        reporter_name = reporter.get("displayName", "None") if reporter else "None"
        reporter_email = reporter.get("emailAddress", "") if reporter else ""

        issues_text += f"""
Ticket {idx}:
Issue Key: {issue_key}
Title: {summary}
URL: {issue_url}
Status: {status}
Priority: {priority}
Type: {issue_type}
Assignee: {assignee_name} <{assignee_email}>
Reporter: {reporter_name} <{reporter_email}>
Created: {created}
Updated: {updated}
Description Preview: {description_preview}

---
"""

    jira_task_memory_query = f"""Find and consolidate information about all people associated with the following {len(issues)} Jira tickets from memory.
Be sure to include **instructions** and information (channel_id, user_id, user_name) for the channel and requesting user.

{issues_text}"""

    # 1. Memory search (for jira task extractor)
    retrieved_memory = await call_memory_retriever(jira_task_memory_query)
    logging.info(
        f"[JIRA_TASK_EXTRACTOR] Memory retrieved: {retrieved_memory[:100] if retrieved_memory else 'None'}..."
    )

    state_prompt = create_state_prompt()

    # Add memory
    state_prompt += f"\n\n## Related Memory\n<retrieved_memory>\n{retrieved_memory}\n</retrieved_memory>"

    system_prompt = create_system_prompt(state_prompt, bot_name)

    # 2. Call jira task extractor
    query = f"""Extract tasks that you need to do from the following {len(issues)} Jira tickets and save them to the database.

{issues_text}

Analyze each ticket and extract specific tasks you need to do (code review, testing, deployment, etc.)."""

    # Atlassian MCP server settings (remote)
    mcp_servers = {
        "atlassian": {
            "command": "npx",
            "args": ["mcp-cache", "npx", "-y", "mcp-remote", "http://localhost:9000/mcp"],
        },
        "jira_tasks": create_jira_tasks_mcp_server(),
    }

    options = ClaudeAgentOptions(
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_SIMPLE,
        permission_mode="bypassPermissions",
        allowed_tools=["*"],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
            "Write",
            "Edit",
            "NotebookEdit",
        ],
        setting_sources=["project"],
        cwd=os.getcwd(),
        mcp_servers=mcp_servers,
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(query)

            result_message = ""
            async for message in client.receive_response():
                if isinstance(message, ResultMessage):
                    result_message = message.result.strip()
                    logging.info(
                        f"[JIRA_TASK_EXTRACTOR] Result: {result_message[:100]}..."
                    )
                    break

            # Return None if no tasks
            if not result_message or (
                "no task" in result_message.lower() and "found" in result_message.lower()
            ):
                logging.info("[JIRA_TASK_EXTRACTOR] No tasks extracted")
                return None

            return result_message

    except Exception as e:
        logging.error(f"[JIRA_TASK_EXTRACTOR] Error: {e}")
        return None