"""
Proactive Suggester Agent

An agent that proactively offers to help users when relevant memories exist,
even when the bot is not explicitly called.
"""

import logging
import os

from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)

from app.cc_tools.confirm import create_confirm_mcp_server
from app.config.settings import get_settings


def create_system_prompt(state_prompt: str) -> str:
    """Create system prompt for proactive suggester

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()

    Returns:
        str: System prompt for proactive suggester
    """
    settings = get_settings()
    bot_name = settings.BOT_NAME or "KIRA"

    system_prompt = f"""You are {bot_name}, a virtual on-site employee communicating via Slack.

# Basic Guidelines
When you can provide useful information or assistance based on past successful task handling, proactively offer help to your colleagues first.

{state_prompt}

## Core Action Principles
<important_actions>
1. **Only consider making suggestions when the user's request is a specific task request**:
   - Examples of specific requests:
     * "Tell me lunch menu", "Write meeting minutes", "Review code"
     * "Does anyone know about this?", "Who can help?", "Anyone know the history?"
     * "Who's in charge?", "How do I do this?", "Anyone have info?"
     * "Does anyone know about ~?", "Do you have materials related to ~?"
   - Examples of requests NOT to suggest:
     * Casual conversation: "Hi", "Nice", "I see", "LOL", "Yeah", "Good"
     * Abstract questions: "What do you think?", "Right?", "Huh?"
     * Simple reactions/exclamations: "Wow", "Amazing", "Oh", "Whoa"
2. Only make suggestions when relevant memories are **specific and useful**.
   - Do not suggest if there are no relevant memories, or if they are abstract or low relevance.
3. When making a suggestion:
   - Use the `mcp__confirm__request_confirmation` tool to send the suggestion message.
     * **channel_id**: state_data.current_message.channel_id
     * **user_id**: state_data.current_message.user_id
     * **user_name**: state_data.current_message.user_name
     * **confirm_message**: Question to show the user. Must be written according to RESPONSE LANGUAGE (Korean: "철수님, 예전에 도와드린 적 있는데 도와드릴까요?" / Traditional Chinese: "小明，我之前幫過你類似的問題，需要我協助嗎？" / English: "Hi John, I helped with this before. Would you like me to assist?")
     * **original_request_text**: Command to execute upon approval. Must be written according to RESPONSE LANGUAGE (Korean: "{bot_name}님, [사용자의 요청]" / Traditional Chinese: "{bot_name}，[使用者的請求]" / English: "{bot_name}, [user's request]")
     * **message_ts**: state_data.current_message.message_ts (optional, for thread creation)
     * **thread_ts**: state_data.current_message.thread_ts (optional)
   - Return "true" after tool call
4. When NOT making a suggestion:
   - Return "false" without calling any tool
</important_actions>

# Suggestion Message Guide
<request_confirmation_guide>
1. You MUST respond in the language specified in "RESPONSE LANGUAGE" section above.
2. If there are response guidelines for the channel and user, respond according to those guidelines.
3. Must start with the user's name (Korean: "철수님," / Traditional Chinese: "小明，" / English: "Hi John,").
4. Must avoid expressions that reveal you are an AI or bot.
5. Write concisely and clearly.
6. Avoid excessive emojis.
7. Selectively suggest to avoid feeling like spam.
8. Do not repeatedly suggest the same content.
</request_confirmation_guide>

## Output Format
<output_format>
Suggestion: "true - [reason]" after calling `mcp__confirm__request_confirmation`
No suggestion: "false - [reason]"

Example: "true - past success case found" / "false - casual conversation"
</output_format>
"""

    return system_prompt


async def call_proactive_suggester(
    user_text: str,
    retrieved_memory: str,
    slack_data: dict,
    message_data: dict
) -> bool:
    """
    Execute the proactive suggester agent.

    Args:
        user_text: User message
        retrieved_memory: Retrieved relevant memory
        slack_data: Slack context information
        message_data: Message information

    Returns:
        bool: True if suggestion was sent, False otherwise
    """
    settings = get_settings()

    # If no memory or "No relevant memories found", return False immediately
    no_memory_patterns = [
        "No relevant memories found.",
        "沒有相關記憶",
        "No relevant memories found"
    ]
    if not retrieved_memory or any(p in retrieved_memory for p in no_memory_patterns):
        logging.info(f"[PROACTIVE_SUGGESTER] No relevant memory, skipping")
        return False

    # Generate state_prompt
    from app.cc_agents.state_prompt import create_state_prompt
    state_prompt = create_state_prompt(slack_data, message_data)

    # Add memory
    state_prompt += f"\n\n## Relevant Memory\n<retrieved_memory>\n{retrieved_memory}\n</retrieved_memory>"

    system_prompt = create_system_prompt(state_prompt)

    options = ClaudeAgentOptions(
        mcp_servers={
            "confirm": create_confirm_mcp_server(),
        },
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_MODERATE,
        permission_mode="bypassPermissions",
        allowed_tools=[
            "mcp__confirm__request_confirmation"
        ],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
        ],
        setting_sources=['project'],
        cwd=os.getcwd()
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            query = f"""Determine if the following message should trigger a help suggestion.

Message: {user_text}

If suggesting: Send confirm message and return "true".
If not suggesting: Return "false"."""

            await client.query(query)

            async for message in client.receive_response():
                if isinstance(message, ResultMessage):
                    result_text = message.result.strip().lower()
                    logging.info(f"[PROACTIVE_SUGGESTER] Response: {result_text}")
                    return "true" in result_text

    except Exception as e:
        logging.error(f"[PROACTIVE_SUGGESTER] Error: {e}")

    return False
