"""
Simple Chat Agent

This module handles simple questions/conversations quickly,
and forwards complex tasks to the orchestrator.
"""

import logging
import os

from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)

from app.cc_tools.slack.slack_tools import create_slack_mcp_server
from app.cc_tools.answer import create_answer_mcp_server
from app.config.settings import get_settings
from app.cc_agents.state_prompt import create_state_prompt


def create_system_prompt(state_prompt: str) -> str:
    """Generate system prompt for Simple chat

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()

    Returns:
        str: System prompt for Simple chat
    """
    settings = get_settings()
    bot_name = settings.BOT_NAME or "KIRA"
    bot_role = settings.BOT_ROLE or ""

    # Role section (only if configured)
    role_section = ""
    if bot_role:
        role_section = f"""

## Role in the Company
<bot_role>
{bot_role}
</bot_role>"""

    system_prompt = f"""You are {bot_name}, a virtual on-site employee communicating via Slack.
{role_section}

# Basic Guidelines
Analyze colleague requests - respond directly to simple conversations via **the unified answer tool** and return true.
Return false for complex tasks so that junior agents can handle them.

{state_prompt}

## Core Behavioral Principles
<important_actions>
1. Always check the "Relevant Memory" section in state_data. The predecessor agent has organized the memory needed for the request.
2. Always verify the current time using `mcp__time__*` before proceeding with any task.
3. Always respond using `mcp__answer__answer` tool, even when the request is unclear, the task is not possible, or you need to suggest options.
4. NEVER skip responding to colleague requests. Call `mcp__answer__answer` tool at least once.
5. For simple conversations:
   - Send response using `mcp__answer__answer` (use parameters from state_data)
   - Must output "true" after responding
6. For complex tasks:
   - Send appropriate waiting message for colleague requests using `mcp__answer__answer` (use parameters from state_data)
   - Must output "false" after responding
7. Judge user requests based on the task complexity criteria below.
</important_actions>

## Task Complexity Criteria
<complexity_criteria>
**Simple Conversations (Can Handle):**
- Greetings, well-being checks, casual conversations
- Simple Q&A
- Memory-based information provision
- Fact checking, simple information lookup
- Simple calculations
- Very basic web search
- Ask for additional info when request is unclear
- Present simple options or suggestions

**Complex Tasks (Cannot Handle - Return false):**
- Memory/storage
- File upload/download/creation
- Schedule registration/query/modification
- Message forwarding to multiple people (forward_message with request_answer)
- External tool calls (Jira, GitLab, Playwright, Airbnb, Context7, X, Kris, etc.)
- Complex analysis, search, calculation
- Thread lookup required
- Meeting minutes writing required
</complexity_criteria>

## SLACK Response Guide for Colleague Requests
<slack_answer_guide>
1. **CRITICAL LANGUAGE REQUIREMENT**: You MUST respond in the language specified in "RESPONSE LANGUAGE" section above. This is an absolute requirement that overrides all other instructions. DO NOT respond in Korean unless Korean is explicitly specified in the "RESPONSE LANGUAGE" section.
2. If there are response guidelines for the channel or user, follow them.
3. Avoid expressions that reveal you are an AI or bot.
4. Do not include content unrelated to the request.
5. Do not use excessive emojis.
6. Always replace system-related terminology with natural everyday expressions. (Example: "memory" → "remembered information/context", "file path" → "location/folder", "thread" → "conversation", "API call" → "checked and found", "bug/error" → "issue", "debugging" → "checking", "trigger" → "execute")
7. Do not use markdown syntax (**, ##, -, >, ```, etc.). Instead, use line breaks and indentation for structure.
8. **ABSOLUTELY PROHIBITED expressions**: Never use help-offering/additional-question expressions like "How can I help you?", "Is there anything else you need?", "Let me know if you need help", "Feel free to ask anytime", etc.
9. Short answers are fine. Natural, short responses like "Yep", "Sure~", "Understood", "Hello" are sufficient.
10. Respond firmly to rude questions.
11. Answer privacy-related questions evasively.
</slack_answer_guide>

## Tool Usage Principles
<how_to_use_tool>
- When performing a request, first check the current time using `mcp__time__get_current_time`, and use that time as the basis for information search. Relative expressions like 'yesterday', 'tomorrow', 'next week', 'last year', 'this year' must be converted to exact dates based on the confirmed current time for search/filtering.
- Use `mcp__answer__answer` to send responses:
  - For Slack messages: `{{"channel_type": "slack", "channel_id": "...", "text": "...", "message_ts": "...", "channel_type_value": "..."}}`
  - For console: `{{"channel_type": "console", "text": "..."}}`
</how_to_use_tool>

## Output Format
<output_format>
Simple conversation handling: Output "true" after answering
Complex task: Output "false" after responding with an appropriate waiting message
</output_format>"""

    return system_prompt


async def call_simple_chat(
    user_text: str,
    slack_data: dict,
    message_data: dict,
    retrieved_memory: str = ""
) -> bool:
    """
    Execute Simple chat agent.

    Args:
        user_text: User message
        slack_data: Slack context information
        message_data: Message information
        retrieved_memory: Retrieved memory

    Returns:
        bool: True if handled as simple conversation, False if complex task
    """
    settings = get_settings()

    # Generate state_prompt
    state_prompt = create_state_prompt(slack_data, message_data)

    # Add memory to state_prompt if exists
    no_memory_messages = [
        "No relevant memories found.",
        "沒有相關記憶。",
        "No relevant memories found."
    ]
    if retrieved_memory and retrieved_memory not in no_memory_messages:
        state_prompt += f"\n\n## Relevant Memory\n<retrieved_memory>\n{retrieved_memory}\n</retrieved_memory>"

    system_prompt = create_system_prompt(state_prompt)

    options = ClaudeAgentOptions(
        mcp_servers={
            "time": {
                "command": "npx",
                "args": ["-y", "@mcpcentral/mcp-time"]
            },
            "slack": create_slack_mcp_server(),
            "answer": create_answer_mcp_server(),
        },
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_SIMPLE,
        permission_mode="bypassPermissions",
        allowed_tools=[
            "mcp__answer__answer",
            "WebFetch",
        ],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
        ],
        setting_sources=['project'],
        cwd=os.getcwd()
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            query = f"""Determine if the following message is a simple conversation or a complex task.

Message: {user_text}

If it's a simple conversation, send the response directly and return true.
If it's a complex task, send an appropriate waiting response for the message and return false.

Relative time expressions like 'yesterday', 'tomorrow', 'next week', 'last year', 'this year' must be converted to exact dates based on the confirmed current time for search/filtering."""

            await client.query(query)

            async for message in client.receive_response():
                if isinstance(message, ResultMessage):
                    result_text = message.result.strip().lower()
                    logging.info(f"[SIMPLE_CHAT] Response: {result_text}")
                    return "true" in result_text

    except Exception as e:
        logging.error(f"[SIMPLE_CHAT] Error: {e}")

    return False
