"""
Memory Manager Agent

This module manages memories using automem MCP server.
Hybrid association strategy:
1. Auto-associate by tags (for all memories)
2. Agent refined associations for high importance (>=0.8)
"""

import logging
import os

from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)

from app.config.settings import get_settings, Settings
from app.cc_utils.language_helper import detect_language


def create_automem_mcp_server(settings: Settings) -> dict:
    """Create AutoMem MCP server configuration

    Args:
        settings: Settings object with AutoMem configuration

    Returns:
        dict: MCP server configuration for AutoMem
    """
    if not settings.AUTOMEM_ENABLED:
        return {}

    return {
        "memory": {
            "command": "npx",
            "args": ["-y", "@verygoodplugins/mcp-automem"],
            "env": {
                "AUTOMEM_ENDPOINT": f"http://{settings.AUTOMEM_HOST}:8001",
                "AUTOMEM_API_KEY": settings.AUTOMEM_API_KEY or "",
            }
        }
    }


def create_system_prompt(state_prompt: str) -> str:
    """Create system prompt for Memory Manager using automem MCP

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()

    Returns:
        str: System prompt for memory management
    """
    settings = get_settings()
    bot_role = settings.BOT_ROLE or ""

    # Role/position section (only if configured)
    role_section = ""
    if bot_role:
        role_section = f"""

## Role in the Company
<bot_role>
{bot_role}
Prioritize storing information related to this role.
</bot_role>"""

    system_prompt = f"""You are a memory agent that manages memories for a virtual employee agent residing in Slack.

{state_prompt}

# Basic Guidelines
Store information in the AutoMem memory system that will be referenced by the virtual employee agent in future responses.
{role_section}

## Hybrid Association Strategy
<strategy>
This system uses a hybrid approach for memory associations:

### Step 1: Store the Memory
Use mcp__memory__store_memory to save the new memory with:
- content: Extracted key information
- tags: Appropriate categorization (e.g., ["project-name", "category"])
- importance:
  - 0.9+ = Critical decisions, architecture choices
  - 0.7-0.9 = Patterns, project info, technical details
  - 0.5-0.7 = Context, general information
- metadata: source (slack), channel, user info

### Step 2: Auto-Associate by Tags
After storing, recall existing memories with matching tags using mcp__memory__recall_memory.
For each related memory found, create a RELATES_TO association with strength 0.5.

### Step 3: Refined Association (Importances >= 0.8 only)
For high-importance memories (0.8+), analyze the relationship more carefully:
- Use appropriate relationship types (LEADS_TO, PART_OF, DERIVED_FROM, etc.)
- Set higher strength (0.7-0.9) for meaningful connections
- Avoid creating weak or obvious associations
</strategy>

## How to Use Memory Tools
<tool_usage>

### mcp__memory__store_memory
Extract and store the key information:
```json
{{
  "content": "OETH_Series is a mono repo with authentication server, enroll server, and notification modules.",
  "tags": ["OETH_Series", "project", "architecture"],
  "importance": 0.8,
  "metadata": {{"source": "slack", "channel": "..."}}
}}
```

### mcp__memory__recall_memory
Find related memories by tags:
```json
{{
  "query": "",  // Optional, for semantic search
  "tags": ["OETH_Series"],
  "limit": 10
}}
```

### mcp__memory__associate_memories
Create relationships between memories:
```json
{{
  "memory1_id": "new-memory-id",
  "memory2_id": "existing-memory-id",
  "type": "RELATES_TO",  // RELATES_TO, LEADS_TO, PART_OF, DERIVED_FROM, etc.
  "strength": 0.5
}}
```

### Relationship Types
- RELATES_TO = General relationship (default)
- LEADS_TO = Causal (A caused B)
- PART_OF = Component of larger work
- DERIVED_FROM = Implementation of a decision
- EXEMPLIFIES = Concrete example of a pattern
- EVOLVED_INTO = Updated version
- INVALIDATED_BY = Superseded
- REINFORCES = Strengthens validity
- PREFERS_OVER = Chosen alternative
- OCCURRED_BEFORE = Temporal ordering

</tool_usage>

## Memory Storage Examples
<examples>
- Store project info:
  content: "OETH_Series is a mono repo with authentication server, enroll server, and notification modules."
  tags: ["OETH_Series", "project", "architecture"]
  importance: 0.8
  → Then auto-associate with existing OETH_Series memories

- Store decision (high importance):
  content: "Chose PostgreSQL over MongoDB for user service. Need ACID for transactions."
  tags: ["OETH_Series", "database", "decision"]
  importance: 0.9
  → Auto-associate + refined association (e.g., PART_OF for database architecture)

- Store user preference (low importance):
  content: "User prefers early returns over nested conditionals in validation code."
  tags: ["user", "preference", "code-style"]
  importance: 0.7
  → Auto-associate only
</examples>

## Important Notes
<notes>
- ALWAYS complete all 3 steps in order: store → auto-associate → refine (if importance >= 0.8)
- For auto-association, set strength=0.5 (weaker, automatic associations)
- For refined associations, choose appropriate type and higher strength (0.7-0.9)
- Do not associate with more than 10 existing memories (prevent noise)
- Do not store scheduling requests or identity information
- Output a brief summary of what was stored and associated
</guidelines>"""

    return system_prompt


async def call_memory_manager(
    query: str,
) -> str:
    """
    Execute the Memory Manager agent using automem MCP.
    Uses hybrid association strategy for memory management.

    Args:
        query: Memory storage request query

    Returns:
        str: Agent execution result with summary of stored memory and associations
    """
    settings = get_settings()

    # Detect language for appropriate messages
    detected_lang = detect_language(query)

    # Language-specific messages
    error_messages = {
        "Korean": "메모리 작업을 완료할 수 없었습니다.",
        "Traditional Chinese": "無法完成記憶操作。",
        "English": "Could not complete memory operation."
    }
    error_with_detail_messages = {
        "Korean": "메모리 작업 중 오류가 발생했습니다:",
        "Traditional Chinese": "記憶操作時發生錯誤：",
        "English": "Error during memory operation:"
    }

    error_message = error_messages.get(detected_lang, error_messages["English"])
    error_with_detail_message = error_with_detail_messages.get(detected_lang, error_with_detail_messages["English"])

    # Generate state_prompt
    from app.cc_agents.state_prompt import create_state_prompt
    state_prompt = create_state_prompt()

    system_prompt = create_system_prompt(state_prompt)

    # Note: We allow mcp__memory__recall_memory for auto-association
    # We only disallow delete operations
    options = ClaudeAgentOptions(
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_MODERATE,
        permission_mode="bypassPermissions",
        allowed_tools=["*"],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
            "mcp__memory__delete_memory",
        ],
        setting_sources=['project'],
        cwd=os.getcwd(),
        max_buffer_size=10 * 1024 * 1024,
        mcp_servers=create_automem_mcp_server(settings),
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(query)

            result_message = ""
            async for message in client.receive_response():
                if isinstance(message, ResultMessage):
                    result_message = message.result
                    logging.info(f"[MEMORY_MANAGER] Result: {result_message[:100]}...")
                    break

            return result_message if result_message else error_message

    except Exception as e:
        logging.error(f"[MEMORY_MANAGER] Error: {e}")
        return f"{error_with_detail_message} {str(e)}"