"""
Memory Manager Agent

This module manages the memories folder, stores information systematically,
and automatically updates the index.md file.
"""

import logging
import os

from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)

from app.config.settings import get_settings
from app.cc_utils.language_helper import detect_language


def create_system_prompt(state_prompt: str, memories_path: str) -> str:
    """Create system prompt for Memory Manager

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()
        memories_path: Absolute path to memories folder

    Returns:
        str: System prompt for memory management
    """
    settings = get_settings()
    bot_role = settings.BOT_ROLE or ""

    # Role/position section (only if configured)
    role_section = ""
    if bot_role:
        role_section = f"""

## Role in the Company
<bot_role>
{bot_role}
Prioritize storing information related to this role.
</bot_role>"""

    system_prompt = f"""You are a memory agent that manages memories for a virtual employee agent residing in Slack.

{state_prompt}

# Basic Guidelines
Store information in {memories_path} that will be referenced by the virtual employee agent in future responses.
{role_section}

## Workflow
<workflow>
1. Always use the `slack-memory-store` skill to manage memories.
2. Analyze the received information and extract appropriate metadata.
3. Use add_memory.py script for automatic classification and storage.
4. Periodically run update_index.py to refresh the index.
</workflow>

## Core Action Principles
<important_actions>
- Always store information related to teammates on your team.
- Include channel info, user info, and Korean names in metadata.
- Save projects using their project names.
- Use tags actively.
- Do not store duplicate content.
</important_actions>

## Guardrail Policy
<guardrails>
- No external access to {memories_path}
- Exclude scheduling requests from storage
- Exclude virtual employee identity information from storage
</guardrails>"""

    return system_prompt


async def call_memory_manager(
    query: str,
) -> str:
    """
    Execute the Memory Manager agent.

    Args:
        query: Memory storage request query

    Returns:
        str: Agent execution result
    """
    settings = get_settings()
    base_dir = settings.FILESYSTEM_BASE_DIR or os.getcwd()
    memories_path = os.path.join(base_dir, "memories")

    # Create memories folder if it doesn't exist
    os.makedirs(memories_path, exist_ok=True)

    # Detect language for appropriate messages
    detected_lang = detect_language(query)

    # Language-specific messages
    error_messages = {
        "Korean": "메모리 작업을 완료할 수 없었습니다.",
        "Traditional Chinese": "無法完成記憶操作。",
        "English": "Could not complete memory operation."
    }
    error_with_detail_messages = {
        "Korean": "메모리 작업 중 오류가 발생했습니다:",
        "Traditional Chinese": "記憶操作時發生錯誤：",
        "English": "Error during memory operation:"
    }

    error_message = error_messages.get(detected_lang, error_messages["English"])
    error_with_detail_message = error_with_detail_messages.get(detected_lang, error_with_detail_messages["English"])

    # Generate state_prompt
    from app.cc_agents.state_prompt import create_state_prompt
    state_prompt = create_state_prompt()

    system_prompt = create_system_prompt(state_prompt, memories_path)

    options = ClaudeAgentOptions(
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_MODERATE,
        permission_mode="bypassPermissions",
        allowed_tools=["*"],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
        ],
        setting_sources=['project'],
        cwd=os.getcwd(),
        max_buffer_size=10 * 1024 * 1024
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(query)

            result_message = ""
            async for message in client.receive_response():

                # from devtools import pprint
                # pprint(message)

                if isinstance(message, ResultMessage):
                    result_message = message.result
                    logging.info(f"[MEMORY_MANAGER] Result: {result_message[:100]}...")
                    break

            return result_message if result_message else error_message

    except Exception as e:
        logging.error(f"[MEMORY_MANAGER] Error: {e}")
        return f"{error_with_detail_message} {str(e)}"
