"""
Memory Retriever Agent

This module searches and aggregates memories related to user queries and returns them.
"""

import logging
import os
from typing import Optional

from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)

from app.config.settings import get_settings
from app.cc_utils.language_helper import detect_language


def create_system_prompt(state_prompt: str, memories_path: str) -> str:
    """Create system prompt for memory retriever

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()
        memories_path: Absolute path to memories folder

    Returns:
        str: System prompt for memory retrieval
    """
    system_prompt = f"""You are an agent that aggregates memories for the virtual employee agent working on Slack.

{state_prompt}

# Basic Guidelines
Use the `slack-memory-retrieval` skill to look up context needed for the answer.

## Workflow
<workflow>
1. Analyze conversation context (channel, user, keywords)
2. Always read {memories_path}/index.md first
3. Load relevant memory files (channels, users, projects, etc.)
4. Synthesize information naturally for the answer
</workflow>

## Memory Exploration Strategy
<retrieval_strategy>
- Channel conversations → Check channels/ first
- DM conversations → Check users/ first
- Project questions → Check projects/
- Decision questions → Check decisions/
- Follow related_to metadata
</retrieval_strategy>

## Guardrail Policy
<guidelines>
- Integrate information naturally without citing sources
- Apply channel/user preferences
- Load only what is needed (avoid excessive queries)
- No access outside {memories_path}
</guidelines>"""

    return system_prompt


async def call_memory_retriever(
    search_query: str,
    slack_data: Optional[dict] = None,
    message_data: Optional[dict] = None
) -> str:
    """
    Execute the memory search agent.

    Args:
        search_query: Memory search query
        slack_data: Slack context information (optional)
        message_data: Message information (optional)

    Returns:
        str: Aggregated memory content
    """
    settings = get_settings()
    base_dir = settings.FILESYSTEM_BASE_DIR or os.getcwd()
    memories_path = os.path.join(base_dir, "memories")

    # Detect language for appropriate messages
    user_text = message_data.get("user_text", "") if message_data else search_query
    detected_lang = detect_language(user_text)

    # Language-specific messages
    no_memory_messages = {
        "Korean": "관련된 메모리가 없습니다.",
        "Traditional Chinese": "沒有相關記憶。",
        "English": "No relevant memories found."
    }
    no_memory_message = no_memory_messages.get(detected_lang, no_memory_messages["English"])

    # Return empty result if memories folder doesn't exist
    if not os.path.exists(memories_path):
        logging.info(f"[MEMORY_RETRIEVER] No memories folder found")
        return no_memory_message

    # Create state_prompt
    from app.cc_agents.state_prompt import create_state_prompt
    state_prompt = create_state_prompt(slack_data, message_data)

    system_prompt = create_system_prompt(state_prompt, memories_path)

    options = ClaudeAgentOptions(
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_SIMPLE,
        permission_mode="bypassPermissions",
        allowed_tools=["*"],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
            "Write",
            "Edit",
            "NotebookEdit",
        ],
        setting_sources=['project'],
        cwd=os.getcwd(),
        max_buffer_size=10 * 1024 * 1024
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(search_query)

            result_message = ""
            async for message in client.receive_response():
                if isinstance(message, ResultMessage):
                    result_message = message.result
                    logging.info(f"[MEMORY_RETRIEVER] Result: {result_message[:100]}...")
                    break

            return result_message if result_message else no_memory_message

    except Exception as e:
        logging.error(f"[MEMORY_RETRIEVER] Error: {e}")
        return no_memory_message
