"""
Memory Retriever Agent

This module searches and aggregates memories from automem MCP server.
"""

import logging
import os
from typing import Optional

from claude_agent_sdk import (
    ClaudeAgentOptions,
    ClaudeSDKClient,
    ResultMessage,
)

from app.config.settings import get_settings, Settings
from app.cc_utils.language_helper import detect_language


def create_automem_mcp_server(settings: Settings) -> dict:
    """Create AutoMem MCP server configuration

    Args:
        settings: Settings object with AutoMem configuration

    Returns:
        dict: MCP server configuration for AutoMem
    """
    if not settings.AUTOMEM_ENABLED:
        return {}

    return {
        "memory": {
            "command": "npx",
            "args": ["-y", "@verygoodplugins/mcp-automem"],
            "env": {
                "AUTOMEM_ENDPOINT": f"http://{settings.AUTOMEM_HOST}:8001",
                "AUTOMEM_API_KEY": settings.AUTOMEM_API_KEY or "",
            }
        }
    }


def create_system_prompt(state_prompt: str) -> str:
    """Create system prompt for memory retriever using automem MCP

    Args:
        state_prompt: Current state prompt generated by create_state_prompt()

    Returns:
        str: System prompt for memory retrieval
    """
    system_prompt = f"""You are an agent that aggregates memories for the virtual employee agent working on Slack.

{state_prompt}

# Basic Guidelines
You have access to the `mcp__memory__recall_memory` tool to search memories in the AutoMem system.

## How to Use mcp__memory__recall_memory
<tool_usage>
1. Construct a natural language query describing what you want to recall
2. Use relevant tags to filter memories (e.g., ["OETH_Series", "project"])
3. Set expand_entities=true to find memories through entity expansion (walks the graph)
4. Set expand_relations=true to follow relationship edges
5. Set appropriate limit (default 5, increase for complex queries)
</tool_usage>

## Query Optimization
<optimization>
- For project questions: Use project name as tag, enable expand_entities
- For decisions: Search with relevant keywords, limit results
- For user preferences: Use user-related tags, limit to recent memories
- For technical details: Combine keyword query + tags, expand entities for related concepts
</optimization>

## Memory Query Examples
<examples>
- Query: "OETH_Series project structure and related repositories"
  query: "OETH_Series project structure"
  tags: ["OETH_Series"]
  expand_entities: true
  expansion_limit: 15

- Query: "user preferences and past decisions"
  query: "user preferences and decisions"
  tags: ["user", "decision"]
  limit: 10
  expand_entities: true

- Query: "authentication system details"
  query: "authentication system technical details"
  tags: ["auth", "OETH_Series"]
  expand_entities: true
  expand_relations: true
  expansion_limit: 20

- Query: "database architecture decisions"
  query: "database architecture choices"
  tags: ["database", "decision"]
  expand_entities: true
</examples>

## Important Notes
<notes>
- AutoMem uses semantic search - describe what you want to recall naturally
- expand_entities=true walks the knowledge graph to find related memories
- Related memories are automatically expanded when expand_entities=true
- Tags help filter by project, category, or other metadata
- If no memories are found, return a brief "No relevant memories found" message
- Synthesize information naturally - do not just list raw memories
</guidelines>"""

    return system_prompt


async def call_memory_retriever(
    search_query: str,
    slack_data: Optional[dict] = None,
    message_data: Optional[dict] = None
) -> str:
    """
    Execute the memory search agent using automem MCP.

    Args:
        search_query: Memory search query
        slack_data: Slack context information (optional)
        message_data: Message information (optional)

    Returns:
        str: Aggregated memory content
    """
    settings = get_settings()

    # Detect language for appropriate messages
    user_text = message_data.get("user_text", "") if message_data else search_query
    detected_lang = detect_language(user_text)

    # Language-specific messages
    no_memory_messages = {
        "Korean": "관련된 메모리가 없습니다.",
        "Traditional Chinese": "沒有相關記憶。",
        "English": "No relevant memories found."
    }
    no_memory_message = no_memory_messages.get(detected_lang, no_memory_messages["English"])

    # Create state_prompt
    from app.cc_agents.state_prompt import create_state_prompt
    state_prompt = create_state_prompt(slack_data, message_data)

    system_prompt = create_system_prompt(state_prompt)

    options = ClaudeAgentOptions(
        system_prompt=system_prompt,
        model=settings.MODEL_FOR_SIMPLE,
        permission_mode="bypassPermissions",
        allowed_tools=["*"],
        disallowed_tools=[
            "Bash(curl:*)",
            "Bash(rm:*)",
            "Bash(rm -r*)",
            "Bash(rm -rf*)",
            "Read(./.env)",
            "Read(./credential.json)",
            "WebFetch",
            "Write",
            "Edit",
            "NotebookEdit",
            "mcp__memory__store_memory",
            "mcp__memory__associate_memories",
            "mcp__memory__update_memory",
            "mcp__memory__delete_memory",
        ],
        setting_sources=['project'],
        cwd=os.getcwd(),
        max_buffer_size=10 * 1024 * 1024,
        mcp_servers=create_automem_mcp_server(settings),
    )

    try:
        async with ClaudeSDKClient(options=options) as client:
            await client.query(search_query)

            result_message = ""
            async for message in client.receive_response():
                if isinstance(message, ResultMessage):
                    result_message = message.result
                    logging.info(f"[MEMORY_RETRIEVER] Result: {result_message[:100]}...")
                    break

            return result_message if result_message else no_memory_message

    except Exception as e:
        logging.error(f"[MEMORY_RETRIEVER] Error: {e}")
        return no_memory_message